version: '3.8'

services:

##############################
# monitored servers
##############################

  webui:
    container_name: webui
    hostname: webui
    image: eclipse-temurin:21
    ports:
      - 8081:8081
    networks:
      - internal
      - external
    volumes:
      - ../webapp/webui:/webui
    working_dir: /webui
    command:
      - /bin/bash
      - -c
      - |
        ./gradlew clean
        ./gradlew bootRun
    tty: true

  webapi:
    container_name: webapi
    hostname: webapi
    image: eclipse-temurin:21
    ports:
      - 8082:8082
    networks:
      - internal
      - external
    volumes:
      - ../webapp/webapi:/webapi
    working_dir: /webapi
    command:
      - /bin/bash
      - -c
      - |
        ./gradlew clean
        ./gradlew bootRun
    tty: true

  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - internal
      - external
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: "Asia/Tokyo"
#    logging:
#      driver: loki
#      options:
#        loki-url: http://localhost:3100/loki/api/v1/push

##############################
# networks
##############################

networks:
  internal:
    name: intra-net
    driver: bridge
    internal: true
  external:
    name: hands-net
    driver: bridge

