version: '3.8'

services:

##############################
# monitored servers
##############################

  webui:
    container_name: webui
    hostname: webui
    build:
      context: ../webapp
      dockerfile: Dockerfile-webui
    image: webapp/webui:latest
    ports:
      - 8181:8181
    networks:
      - internal
      - external
    working_dir: /webui
    command:
      - /bin/bash
      - -c
      - |
        wget -O ./pyroscope.jar https://github.com/grafana/pyroscope-java/releases/download/v2.0.0/pyroscope.jar
        java -javaagent:pyroscope.jar -jar build/libs/apisl.handson.grafana.webapp.webui-0.0.1-SNAPSHOT.jar
    environment:
      PYROSCOPE_APPLICATION_NAME: webapp.webui
      PYROSCOPE_SERVER_ADDRESS: http://alloy:9999
      PYROSCOPE_FORMAT: jfr
      PYROSCOPE_PROFILER_ALLOC: 512k
      PYROSCOPE_PROFILER_LOCK: 10ms
    tty: true

  webapi:
    container_name: webapi
    hostname: webapi
    build:
      context: ../webapp
      dockerfile: Dockerfile-webapi
    image: webapp/webapi:latest
    ports:
      - 8182:8182
    networks:
      - internal
      - external
    working_dir: /webapi
    command:
      - /bin/bash
      - -c
      - |
        wget -O ./pyroscope.jar https://github.com/grafana/pyroscope-java/releases/download/v2.0.0/pyroscope.jar
        java -javaagent:pyroscope.jar -jar build/libs/apisl.handson.grafana.webapp.webapi-0.0.1-SNAPSHOT.jar
    environment:
      PYROSCOPE_APPLICATION_NAME: webapp.webapi
      PYROSCOPE_SERVER_ADDRESS: http://alloy:9999
      PYROSCOPE_FORMAT: jfr
      PYROSCOPE_PROFILER_ALLOC: 512k
      PYROSCOPE_PROFILER_LOCK: 10ms
    tty: true

  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - internal
      - external
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: "Asia/Tokyo"
#    logging:
#      driver: loki
#      options:
#        loki-url: http://localhost:3100/loki/api/v1/push

  webui-node-exporter:
    hostname: webui-node-exporter
    container_name: webui-node-exporter
    image: &nodeExpImage prom/node-exporter:v1.9.1
    pid: "service:webui"
    networks:
      - internal
  webapi-node-exporter:
    hostname: webapi-node-exporter
    container_name: webapi-node-exporter
    image: *nodeExpImage
    pid: "service:webapi"
    networks:
      - internal

##############################
# networks
##############################

networks:
  internal:
    name: intra-net
    driver: bridge
    internal: true
  external:
    name: hands-net
    driver: bridge

