server:
  port: 8181

spring:
  application:
    name: webui-app-yml

# variables for spring-boot-starter-actuator
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 5s
        resourceAttributes:
          service.name: webui
          service.instance.id: webui:8181
#    logging:
#      endpoint: http://otel-collector:4318/v1/logs
#    tracing:
#      endpoint: http://otel-collector:4318/v1/traces

# variables for 'io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter'
otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4318
  service:
    name: webui
  log:
    level: debug

# variables for hands-on training
handson:
  webapi:
    host: webapi:8182
#    host: localhost:8182
