apiVersion: 1

datasources:

  - name: "Mimir for Metrics"
    type: prometheus
    uid: mimir-tenant-metrice
    access: proxy
    orgId: 1
    url: http://mimir-lb:9009/prometheus
    editable: true
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
        - name: trace_id
          url: http://localhost:16686/trace/$${__value.raw}
          urlDisplayLabel: "Ref.) Jump to an external tool: Jaeger"
        - name: trace_id
          url: http://localhost:9411/zipkin/traces/$${__value.raw}
          urlDisplayLabel: "Ref.) Jump to an external tool: Zipkin"
    secureJsonData:
      httpHeaderValue1: "tenant-metrics"

  - name: "Mimir for Trace"
    type: prometheus
    uid: mimir-tenant-trace
    access: proxy
    orgId: 1
    url: http://mimir-lb:9009/prometheus
    editable: true
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
    secureJsonData:
      httpHeaderValue1: "tenant-trace"

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki-lb:9009
    editable: true
    isDefault: true
    jsonData:
      derivedFields:
        - name: trace_id
          datasourceUid: tempo
          matcherType: label
          matcherRegex: trace_id
          url: $${__value.raw}
        - name: Jaeger
          matcherType: label
          matcherRegex: trace_id
          targetBlank: true
          url: http://localhost:16686/trace/$${__value.raw}
          urlDisplayLabel: "Ref.) Jump to an external tool: Jaeger"
        - name: Zipkin
          matcherType: label
          matcherRegex: trace_id
          targetBlank: true
          url: http://localhost:9411/zipkin/traces/$${__value.raw}
          urlDisplayLabel: "Ref.) Jump to an external tool: Zipkin"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo-lb-view:9009
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: mimir-tenant-trace
      tracesToLogs:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1s'
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: mimir-tenant-metrice
        queries:
          - name: p99 latency
            query: "histogram_quantile(.99, sum(rate(http_server_requests_seconds_bucket{$__tags}[1m])) by (le))"
        spanStartTimeShift: -10m
        spanEndTimeShift: 10m
        tags:
          - key: service.name
            value: server_address
          - key: job
            value: ""

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    orgId: 1
    url: http://pyroscope:4040
    editable: true
    isDefault: false

