stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: debug

distributor:
  ring:
    kvstore:
      store: memberlist
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: ":14268"
        grpc:
          endpoint: ":14250"
        thrift_binary:
          endpoint: ":6832"
        thrift_compact:
          endpoint: ":6831"
    zipkin:
      endpoint: ":9411"
    otlp:
      protocols:
        grpc:
          endpoint: ":4317"
        http:
          endpoint: ":4318"
    opencensus:
      endpoint: ":55678"

ingester:
  lifecycler:
    ring:
      replication_factor: 2
      kvstore:
        store: memberlist

compactor:
  ring:
    kvstore:
      store: memberlist

metrics_generator:
  ring:
    kvstore:
      store: memberlist
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://mimir-lb:9009/api/v1/push
        send_exemplars: true
        headers:
          X-Scope-OrgID: tenant-trace
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio-tempo:9000
      access_key: tempo
      secret_key: password
      insecure: true
      bucket: tempo

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
      generate_native_histograms: both

memberlist:
  join_members:
    - tempo-1:7946
    - tempo-2:7946
