{
 "title": "My Real-time User Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app_name=\"$app\"} |= \"ttfb\" | logfmt | kind = `measurement` | unwrap ttfb [$__range]) by (app_name)",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app_name=\"$app\"} |= \" fcp=\" | logfmt | kind = `measurement` | unwrap fcp [$__range]) by (app_name)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app_name=\"$app\"} |= \" lcp=\" | logfmt | kind = `measurement` | unwrap lcp [$__range]) by (app_name)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app_name=\"$app\"} |= \"cls\" | logfmt | kind = `measurement` | unwrap cls [$__range]) by (app_name)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({app_name=\"$app\"} |= \" fid=\" | logfmt | kind = `measurement` | unwrap fid [$__range]) by (app_name)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {app_name=\"$app\"} |= \" ttfb=\" | logfmt | kind = `measurement` | unwrap ttfb [5m]) by (app_name)",
     "legendFormat": "TTFB"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [5m]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [5m]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {app_name=\"$app\"} |= \" cls=\" | logfmt | kind = `measurement` | unwrap cls [5m]) by (app_name)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {app_name=\"$app\"} |= \" fid=\" | logfmt | kind = `measurement` | unwrap fid [5m]) by (app_name)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Popular OS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 141 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} |= \" ttfb=\" | logfmt | kind = `measurement` [$__range])) by (browser_os))"
      }
     ]
    },
    {
     "title": "Popular Browsers",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 141 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} |= \" ttfb=\" | logfmt | kind = `measurement` [$__range])) by (browser_name, browser_version))"
      }
     ]
    },
    {
     "title": "Popular Viewports",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 141 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} |= \" ttfb=\" | logfmt | kind = `measurement` [$__range])) by (browser_viewportWidth, browser_viewportHeight))"
      }
     ]
    },
    {
     "title": "Visits",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 226 },
     "targets": [
      {
       "direction": "backward",
       "expr": "count_over_time({app_name=\"$app\"} |= \" kind=measurement\" |= \" ttfb=\" [$__interval])",
       "legendFormat": "visits"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Exceptions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 142 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum(count_over_time({app_name=\"$app\"} | logfmt | kind = `exception` [$__range])) by (app_name)"
      }
     ]
    },
    {
     "title": "Exceptions Over Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 142 },
     "targets": [
      {
       "direction": "backward",
       "expr": "count_over_time({app_name=\"$app\"} | logfmt | kind = `exception` [$__interval])",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Top Exceptions",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 142 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} | logfmt | kind = `exception` [$__range])) by (value))"
      }
     ]
    },
    {
     "title": "Top URLs by Exception Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 213 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} | logfmt | kind = `exception` [$__range])) by (page_url))"
      }
     ]
    },
    {
     "title": "Top Browsers by Exception Count",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 213 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({app_name=\"$app\"} | logfmt | kind = `exception` [$__range])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 143 },
     "targets": [
      {
       "direction": "backward",
       "expr": "topk(10, count(count_over_time({app_name=\"$app\"} |= \"kind=event\" | logfmt [$__range])) by (event_name))"
      }
     ]
    }
   ]
  },
  {
   "title": "Faro log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Faro log",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{app_name=\"$app\"} | logfmt"
      }
     ]
    }
   ]
  },
  {
   "title": "Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Faro Traces",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "limit": 20,
       "query": "{resource.service.name=\"$app\"}",
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}