apiVersion: 1

groups:

  - name: "Eval Interval - 10s"
    orgId: 1
    folder: "Hands-on Training"
    interval: 10s
    rules:
      - uid: error-level-webui-log
        title: "Error level - WebUI log"
        condition: C
        data:
          - refId: A
            queryType: instant
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: loki
            model:
              editorMode: builder
              expr: sum by (message)(count_over_time({service_name="webui"} | detected_level = `error` [1m]))
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: instant
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
                  unloadEvaluator:
                    params:
                      - 0
                    type: lt
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        annotations: {}
        labels: {}
        isPaused: false
        notification_settings:
          receiver: "Hands-on Recieve E-mail"
